---
title: "Chapter 7 - Multidimensional Item Response Theory"
format: html
editor: visual
---

```{r}
library(hemp)
library(mirt)
```

```{r}
mimic
```

```{r}
m2pl_mod<-'F1=1-6,13-21,23-24
F2=7-20,22-24
COV=F1*F2'
```

```{r}
m2pl_fit<-mirt(data=mimic,
               model=m2pl_mod,
               itemtype = "2PL",
               method = "EM",
               SE=TRUE)
m2pl_fit
```

```{r}
m2pl_params<-coef(m2pl_fit,simplify=TRUE)
m2pl_params
```

```{r}
m2pl_params$items
```

```{r}
m2pl_items<-data.frame(MDISC(m2pl_fit),
                       MDIFF(m2pl_fit))
colnames(m2pl_items)<-c("m2pl_mdisc","m2pl_mdiff")
m2pl_items
```

```{r}
m2pl_params$cov
```

```{r}
itemplot(m2pl_fit,type="trace",item=13)
```

```{r}
itemplot(m2pl_fit,type="tracecontour",item=13)
```

```{r}
itemplot(m2pl_fit,type="info",item=13)
```

```{r}
itemplot(m2pl_fit,type="infocontour",item=13)
```

```{r}
itemplot(m2pl_fit,type="score",item=13)
```

```{r}
itemplot(m2pl_fit,type="SE",item=13)
```

```{r}
itemplot(m2pl_fit,type="trace",item=1)
itemplot(m2pl_fit,type="tracecontour",item=1)
itemplot(m2pl_fit,type="info",item=1)
itemplot(m2pl_fit,type="infocontour",item=1)
itemplot(m2pl_fit,type="score",item=1)
itemplot(m2pl_fit,type="SE",item=1)
```

```{r}
m2pl_map<-fscores(m2pl_fit,method="MAP",full.scores = TRUE,full.scores.SE = TRUE)
m2pl_map
```

```{r}
m2pl_eap<-fscores(m2pl_fit,method="EAP",full.scores = TRUE,full.scores.SE = TRUE)
head(m2pl_eap)
```

```{r}
m2pl_scores<-data.frame(map1=m2pl_map[,1],
                        map2=m2pl_map[,2],
                        eap1=m2pl_eap[,1],
                        eap2=m2pl_eap[,2])
head(m2pl_scores)
```

```{r}
cor(m2pl_scores)
```

```{r}
m2pl_mod_constrant<-'
F1=1-6,13-21,23-24
F2=7-20,22-24
COV=F1*F2
CONSTRAIN=(1-6,21,a1), (7-12,22,a2)'
```

```{r}
m2pl_constrant_fit<-mirt(data=mimic,model=m2pl_mod_constrant,itemtype = "2PL",SE=TRUE)
coef(m2pl_constrant_fit,simplify=TRUE)
```

```{r}
m2pl_fit_noncomp<-mirt(data=mimic,model=m2pl_mod,itemtype="PC2PL",SE=TRUE)
coef(m2pl_fit_noncomp,simplify=TRUE)
```

```{r}
MDISC(m2pl_constrant_fit)
```

```{r}
MDISC(m2pl_fit_noncomp)
```

```{r}
MDIFF(m2pl_constrant_fit)
```

```{r}
mrasch_mod<-'F1=1-6,13-21,23-24
F2=7-20,22-24
COV=F1*F2'

mrasch_fit<-mirt(data=mimic,model=mrasch_mod,itemtype = "Rasch",SE=TRUE)
mrasch_params<-coef(mrasch_fit,simplify=TRUE)
mrasch_params
```

```{r}
mrasch_diff<-MDIFF(mrasch_fit)
mrasch_diff
```

```{r}
mrasch_params$cov
```

```{r}
itemplot(mrasch_fit,type="trace",item=13)
itemplot(mrasch_fit,type="tracecontour",item=13)
plot(mrasch_fit,type="info")
plot(mrasch_fit,type="SE")
plot(mrasch_fit,type="score")
```

```{r}
mgrm_mod<-'Cognitive=1-10
Somatic=11-20
COV=Cognitive*Somatic'
```

```{r}
mgrm_fit<-mirt(data=depression,model=mgrm_mod,itemtype = "graded",SE=TRUE)
mgrm_params<-coef(mgrm_fit,simplify=TRUE)
mgrm_params$items
```

```{r}
mgrm_items<-cbind(MDISC(mgrm_fit),MDIFF(mgrm_fit))
mgrm_items
```

```{r}
mgrm_params$cov
```

```{r}
itemplot(mgrm_fit,type="trace",item=7)
itemplot(mgrm_fit,type="trace",item=13)
plot(mgrm_fit,type="info")
plot(mgrm_fit,type="SE")
plot(mgrm_fit,type="score")
```

```{r}
dimensions<-rep(c(1,2),each=10)
bifactor_fit<-bfactor(data=depression,model=dimensions)
bifactor_params<-coef(bifactor_fit,simplify=TRUE)
bifactor_params$items
```

```{r}
bifactor_items<-cbind(MDISC(bifactor_fit),MDIFF(bifactor_fit))
bifactor_items
```

```{r}
bifactor_params$cov
```
