---
title: "Chapter 5 - Item Response Theory for Dichotomous Items"
format: html
editor: visual
---

```{r}
library(mirt)
library(hemp)
```

```{r}
onepl_mod<-"F=1-16
CONSTRAIN=(1-16,a1)"
```

```{r}
onepl_fit<-mirt(data=SAPA,model=onepl_mod,SE=TRUE)
onepl_fit
```

```{r}
summary(onepl_fit)
```

```{r}
onepl_params<-coef(onepl_fit,IRTpars=TRUE,simplify=TRUE)
onepl_params
```

```{r}
onepl_items<-onepl_params$items
onepl_items
```

```{r}
onepl_se<-coef(onepl_fit,printSE=TRUE)
onepl_se
```

```{r}
plot(onepl_fit,type="trace",which.items=1:2)
```

```{r}
itemplot(onepl_fit,type="trace",item=1)
```

```{r}
plot(onepl_fit,type="infotrace",which.items=c(3,5))
```

```{r}
plot(onepl_fit,type="trace",which.items=1:2,facet_items=FALSE,
     auto.key=list(points=FALSE,lines=TRUE,columns=2),
     par.settings=simpleTheme(lty=1:2))
```

```{r}
library(latticeExtra)
```

```{r}
plot(onepl_fit,type="infoSE",theta_lim=c(-3,3))
```

```{r}
rasch_mod<-"F=1-16"
rasch_fit<-mirt(data=SAPA,model=rasch_mod,itemtype="Rasch",SE=TRUE)
rasch_fit
```

```{r}
coef(rasch_fit,printSE=TRUE)
```

```{r}
rasch_params<-coef(rasch_fit,IRTpars=TRUE,simplify=TRUE)
rasch_items<-rasch_params$items
rasch_items
```

```{r}
plot(rasch_fit,type="trace",which.items=c(1,2))
```
```{r}
twwopl_mod<-"F=1-16"
twopl_fit<-mirt(data=SAPA,model=twwopl_mod,itemtype="2PL",SE=TRUE)
twopl_fit
```

```{r}
twopl_params<-coef(twopl_fit,IRTpars=TRUE,simplify=TRUE)
twopl_items<-twopl_params$items
twopl_items
```

```{r}
plot(twopl_fit,type="trace",which.items=c(12,14))
```
```{r}
plot(twopl_fit,type="trace",which.items=c(5,16),
     facet_items=FALSE,auto.key=list(points=FALSE),lines=TRUE,columns=2,par.settings=simpleTheme(lty=1:2))
```

```{r}
threepl_mod<-"F=1-16"
threepl_fit<-mirt(data=SAPA,model=threepl_mod,itemtype = "3PL",SE=TRUE)
threepl_fit
```

```{r}
threepl_params<-coef(threepl_fit,IRTpars=TRUE,simplify=TRUE)
threepl_items<-threepl_params$items
threepl_items
```
```{r}
plot(threepl_fit,type="trace",which.items=c(1,4),
     facet_items=FALSE,auto.key=list(points=FALSE,lines=TRUE,columns=2),
     par.settings=simpleTheme(lty=1:2))
```

```{r}
fourpl_mod<-"F=1-16"
fourpl_fit<-mirt(data=SAPA,model=fourpl_mod,itemtype = "4PL",SE=TRUE)
fourpl_fit
```

```{r}
fourpl_params<-coef(fourpl_fit,IRTpars=TRUE,simplify=TRUE)
fourpl_items<-fourpl_params$items
fourpl_items
```
```{r}
plot(fourpl_fit,type="trace",which.items=c(13,16))
```

```{r}
latent_mle<-fscores(twopl_fit,method="ML",full.scores = TRUE,full.scores.SE = TRUE)
latent_map<-fscores(twopl_fit,method="MAP",full.scores=TRUE,full.scores.SE = TRUE)
latent_eap<-fscores(twopl_fit,method="EAP",full.scores = TRUE,full.scores.SE = TRUE)
```

```{r}
head(latent_mle)
```

```{r}
latent<-data.frame(MLE=latent_mle[,1],
                   MAP=latent_map[,1],
                   EAP=latent_eap[,1])
head(latent)
```

```{r}
latent[c(73,89,103,105),]
```

```{r}
latent_est<-latent[is.finite(latent$MLE),]
```

```{r}
apply(latent_est,2,summary)
apply(latent_est,2,sd)
```

```{r}
cor(latent_est)
```
```{r}
pairs(latent_est)
```
```{r}
rmsd(latent_est$MLE,latent_est$MAP)
rmsd(latent_est$MLE,latent_est$EAP)
rmsd(latent_est$MAP,latent_est$EAP)
```

```{r}
rasch_itemfit<-itemfit(rasch_fit,
                       fit_stats = c("S_X2","G2"),
                       na.rm = TRUE)
rasch_itemfit
```

```{r}
itemfit(rasch_fit,fit_stats = c("Zh","infit"),na.rm = TRUE)
```



```{r}
itemfit(rasch_fit,empirical.plot = 1)
```


```{r}
SAPA_nomiss<-na.omit(SAPA)
rasch_mod<-"F=1-16"
rasch_fit<-mirt(data=SAPA_nomiss,model=rasch_mod,itemtype = "Rasch",SE=TRUE,verbose = FALSE)
rasch_personfit<-personfit(rasch_fit)
head(rasch_personfit)
```

```{r}
hist(rasch_personfit$Zh,xlab="Zh Statistic")
abline(v=-2,lwd=2,lty=2)
```

```{r}
rasch_misfits<-subset(rasch_personfit,Zh< -2)
rownames(rasch_misfits)
```

```{r}
nrow(rasch_misfits)
```

```{r}
anova(onepl_fit,twopl_fit)
```

```{r}
anova(twopl_fit,threepl_fit)
```

```{r}
anova(threepl_fit,fourpl_fit)
```

