---
title: "Chapter 4 - Factor Analytic Approach in Measurement"
format: html
editor: visual
---

```{r}
library(hemp)
cognition<-subset(interest,select=vocab:analyrea)
```
```{r}
summary(cognition)
```
```{r}
apply(cognition,2,var)
```
```{r}
library(lattice)
cognition_1<-reshape(data=cognition,
                     varying=1:6,
                     v.names = "score",
                     timevar = "indicator",
                     times = names(cognition),
                     direction = "long")
cognition_1[order(cognition_1$id),]
```

```{r}
histogram(~score|indicator,data=cognition_1)
```
```{r}
pairs(cognition)
```
```{r}
bollen_plot(cognition,crit.value = .06)
```

```{r}
cognition[c(202,53,111),]
```

```{r}
apply(cognition,2,min)
```


```{r}
apply(cognition,2,max)
```

```{r}
correlations<-cor(cognition)
round(correlations,3)
```

```{r}
corr_diff<-correlations-cor(cognition[-c(202,53,101),])
round(corr_diff,3)
```

```{r}
eigen_decomp<-eigen(correlations)
round(eigen_decomp$values,3)
```

```{r}
lattice_scree(cognition)
```
```{r}
library(psych)
fa.parallel(cognition,fm="ml")
```

```{r}
lattice_pa(cognition)
```

```{r}
one_factor<-factanal(cognition,factors = 1)
one_factor
```
```{r}
two_factor<-factanal(cognition,factors=2)
two_factor
```

```{r}
#install.packages("GPArotation")
library(GPArotation)
oblimin(loadings(two_factor))
```

```{r}
library(psych)
fa(r=cognition,nfactors=2,rotate="oblimin")
```

```{r}
SAPA_subset<-subset(SAPA,select=c(letter.7:letter.58,rotate.3:rotate.8))
```

```{r}
fa.parallel(SAPA_subset,cor="poly")
```

```{r}
EFA_SAPA<-fa(SAPA_subset,2,rotate="oblimin",cor="poly")
EFA_SAPA
```

```{r}
SAPA_cor<-polychoric(SAPA_subset)
```


```{r}
factanal(covmat=SAPA_cor$rho,factors=2,n.obs=nrow(SAPA))
```

```{r}
library(lavaan)
```

```{r}
iq_mod<-'
verb=~info+comp+arith+simil+digit+vocab
perf=~pictcomp+parang+block+object+coding'
```

```{r}
iq_fit<-cfa(iq_mod,data=wiscsem)
```

```{r}
inspect(iq_fit)
```

```{r}
summary(iq_fit)
```
```{r}
unique_elements(iq_fit)
```

```{r}
free_params(iq_fit)
```

```{r}
summary(iq_fit,standardized=TRUE,fit.measures=TRUE)
```
```{r}
fitmeasures(iq_fit)
```
```{r}
inspect(iq_fit,"rsquare")
```

```{r}
summary(iq_fit,rsquare=TRUE)
```

```{r}
summary(iq_fit,standardized=TRUE,fit.measures=TRUE,rsquare=TRUE)
```
```{r}
iq_mod_nocode<-'
verb=~info+comp+arith+simil+digit+vocab 
perf=~pictcomp+parang+block+object'
```

```{r}
iq_fit_nocode<-cfa(iq_mod_nocode,wiscsem)
```

```{r}
summary(iq_fit_nocode)
```

```{r}
nocode<-fitmeasures(iq_fit_nocode,fit.measures = c("rmsea","tli","cfi"))
code<-fitmeasures(iq_fit,fit.measures = c("rmsea","tli","cfa"))
rbind(nocode,code)
```

```{r}
anova(iq_fit_nocode,iq_fit) #based on different set of observed vars so not considered to be nested
```
```{r}
modind_iq<-modindices(iq_fit_nocode,sort=TRUE)
modind_iq[modind_iq$mi>3.84,]
```
```{r}
iq_mod_mi<-'
verb=~info+comp+arith+simil+digit+vocab
perf=~pictcomp+parang+block+object+comp
'

iq_fit_mi<-cfa(iq_mod_mi,wiscsem)
fitmeasures(iq_fit_mi,c("rmsea","tli","cfi","srmr"))
```

```{r}
summary(iq_fit_mi)
```

```{r}
anova(iq_fit_nocode,iq_fit_mi)
```
```{r}
anova(iq_fit,iq_fit_mi)
```
```{r}
factor_scores<-predict(iq_fit_mi)
head(factor_scores)
```
```{r}
fitted(iq_fit_mi)
```

```{r}
residuals(iq_fit_mi)
```

```{r}
wiscsem_cat<-wiscsem
wiscsem_cat[,]<-lapply(wiscsem_cat[,],quart_cut)
```

```{r}
wiscsem_ord<-wiscsem_cat
wiscsem_ord[,]<-lapply(wiscsem_ord[,],ordered)
```

```{r}
iq_fit_ord1<-cfa(iq_mod,wiscsem_ord)
summary(iq_fit_ord1)
```

```{r}
iq_fit_ord2<-cfa(iq_mod,wiscsem_cat,ordered=names(wiscsem_cat))
summary(iq_fit_ord2)
```

