---
title: "Chapter 3 - Generalizability Theory"
format: html
editor: visual
---

```{r}
library(hemp)
```

```{r}
efData
```

```{r}
onefacet_mod<-lmer(Score~(1|Participants)+(1|Items),data=efData)
onefacet<-gstudy(onefacet_mod)

summary(onefacet_mod)
```

```{r}
onefacet
```

```{r}
library(lattice)
scores<-aggregate(efData$Score,by=list(efData$Participants),mean)
scores
```

```{r}
histogram(~x,scores,type="count",xlab="Proportion of Items Correct")
```

```{r}
item_means<-aggregate(efData$Score,by=list(efData$Items),mean)
colnames(item_means)<-c("Item","Mean")
item_means
```

```{r}
dstudy(onefacet,unit="Participants",n=c("Items"=1))
```

```{r}
onefacet_dstudy<-dstudy(onefacet,unit="Participants",n=c("Items"=10))
onefacet_dstudy
```

```{r}
onefacet_dstudy$relvar
onefacet_dstudy$absvar
```

```{r}
dstudy_plot(onefacet,unit="Participants",
            facets=list(Items=c(10,20,30,40,50,60)),
            g_coef=FALSE)
```

```{r}
writing
```

```{r}
twofacet_mod<-lmer(scores~(1|students)+(1|prompts)+(1|raters)+(1|students:prompts)+(1|students:raters)+(1|prompts:raters),data=writing)
twofacet_mod
```

```{r}
twofacet<-gstudy(twofacet_mod)
twofacet
```

```{r}
dstudy(twofacet,n=c("raters"=2,"prompts"=5),unit="students")
```

```{r}
dstudy_plot(twofacet,unit="students",facets=list(prompts=3:8,raters=1:5))
```

```{r}
writing2
```

```{r}
nested_model<-lmer(scores~(1|students/raters)+(1|prompts)+(1|students:prompts),data=writing2)
nested<-gstudy(nested_model)
nested
```

```{r}
dstudy(nested,n=c("raters"=2,"prompts"=5),unit="students")
```

```{r}
twofacet_fixed<-gstudy(twofacet_mod,fixed = "prompts")
twofacet_fixed
```

```{r}
dstudy(twofacet_fixed,n=c("raters"=2,"prompts"=5),unit="students")
```
