---
title: "Chapter 6 - Item Response Theory for Polytomous Items"
format: html
editor: visual
---

```{r}
library(hemp)
library(mirt)
```

```{r}
head(rse)
```

```{r}
pcm_mod<-"selfesteem=1-10"
pcm_fit<-mirt(rse[,1:10],model=pcm_mod,itemtype = "Rasch",SE=TRUE)
pcm_fit
```

```{r}
pcm_params<-coef(pcm_fit,IRTpars=TRUE,simplify=TRUE)
```

```{r}
pcm_params
```

```{r}
pcm_items<-as.data.frame(pcm_params$items)
pcm_items
```

```{r}
plot(pcm_fit,type="trace",which.items=c(2,5),par.settings=simpleTheme(lty=1:4,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=4))
```

```{r}
plot(pcm_fit,type="trace",par.settings=simpleTheme(lty=1:4,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=4))
```

```{r}
plot(pcm_fit,type="infotrace",which.items=c(2,5),par.settings=simpleTheme(lwd=2))
```

```{r}
plot(pcm_fit,type="info",theta_lim=c(-6,6))
plot(pcm_fit,type="SE",theta_lim=c(-6,6))
```

```{r}
rsm_mod<-"selfesteem=1-10"
rsm_fit<-mirt(data=rse[,1:10],model=rsm_mod,itemtype = "rsm")
rsm_params<-coef(rsm_fit,simplify=TRUE)
rsm_items<-as.data.frame(rsm_params$items)
rsm_items
```

```{r}
plot(rsm_fit,type="trace",which.items=c(2,9),par.settings=simpleTheme(lty=1:4,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=4))
```

```{r}
plot(rsm_fit,type="info",theta_lim=c(-6,6))
plot(rsm_fit,type="SE",theta_lim=c(-6,6))
```

```{r}
gpcm_mod<-"selfesteem=1-10"
gpcm_fit<-mirt(data=rse[,1:10],model=gpcm_mod,itemtype = "gpcm",SE=TRUE)
gpcm_params<-coef(gpcm_fit,IRTpars=TRUE,simplify=TRUE)
gpcm_items<-gpcm_params$items
gpcm_items
```

```{r}
plot(gpcm_fit,type="trace",which.items=c(6,8),par.settings=simpleTheme(lty=1:4,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=4))
```

```{r}
plot(gpcm_fit,type="info",theta_lim=c(-6,6))
plot(gpcm_fit,type="SE",theta_lim=c(-6,6))
```

```{r}
grm_mod<-"selfesteem=1-10"
grm_fit<-mirt(data=rse[,1:10],model=grm_mod,itemtype = "graded",SE=TRUE)
grm_params<-coef(grm_fit,IRTpars=TRUE,simplify=TRUE)
grm_items<-as.data.frame(grm_params$items)
grm_items
```

```{r}
plot(grm_fit,type="trace",which.items=c(5,9),par.settings=simpleTheme(lty=1:4,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=4))
```

```{r}
plot(grm_fit,type="info",theta_lim=c(-6,6))
plot(grm_fit,type="SE",theta_lim=c(-6,6))
```

```{r}
VerbAggWide
```

```{r}
colnames(VerbAggWide)
```

```{r}
nrm_mod<-"agression=1-24"
nrm_fit<-mirt(data=VerbAggWide[,4:27],model=nrm_mod,itemtype = "nominal",SE=TRUE)
nrm_params<-coef(nrm_fit,IRTpars=TRUE,simplify=TRUE)
nrm_items<-as.data.frame(nrm_params$items)
nrm_items
```

```{r}
sum_constraints<-data.frame(
        discrimination=round(rowSums(nrm_items[,1:3],3)),
        difficulty=round(rowSums(nrm_items[,4:6],3))
)
sum_constraints
```

```{r}
plot(nrm_fit,type="trace",which.items=c(3,15),
     par.settings=simpleTheme(lty=1:3,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=3))
```

```{r}
itemplot(nrm_fit,item=15,CE=TRUE)
```

```{r}
plot(nrm_fit,type="info",theta_lim=c(-6,6))
```

```{r}
key=c(4,3,2,3,4,3,2,3,1,
      4,3,2,3,3,4,2,4,3,
      3,2,2,1,2,1,1,2,1)
twoplnlm_mod<-"ability=1-27"
twoplnlm_fit<-mirt(data=multiplechoice,
                   model=twoplnlm_mod,
                   itemtype = "2PLNRM",
                   SE=TRUE,
                   key=key)
twoplnlm_params<-coef(twoplnlm_fit,IRTpars=TRUE,simplify=TRUE)
twoplnlm_items<-as.data.frame(twoplnlm_params$items)
twoplnlm_items
```
```{r}
plot(twoplnlm_fit,type="trace",which.items=c(8,21),par.settings=simpleTheme(lty=1:4,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=4))
```

```{r}
threeplnlm_mod<-"ability=1-27"
threeplnlm_fit<-mirt(data=multiplechoice,
                     model=threeplnlm_mod,
                     itemtype = "3PLNRM",
                     SE=TRUE,
                     key=key)
threeplnlm_params<-coef(threeplnlm_fit,IRTpars=TRUE,simplify=TRUE)
threeplnlm_items<-as.data.frame(threeplnlm_params$items)
threeplnlm_items
```

```{r}
plot(threeplnlm_fit,type="trace",which.items=c(1,17),par.settings=simpleTheme(lty=1:4,lwd=2),
     auto.key=list(points=FALSE,lines=TRUE,columns=4))
```

