---
title: "Chapter 1 - Introduction to the R Programming Language"
format: html
editor: visual
---

```{r}
2+2
```

```{r}
# The following R code calculates the sum of 2 and 2
2+2
```

```{r}
6+20
89-53
424*68
1110/37
```

```{r}
log(10)
```

```{r}
x<-1
x
X
```

```{r}
x<-c(1,5,3,6,9)
```

```{r}
gender<-c("male","male","male","female","female","female")
x_f<-as.factor(x)
gender_f<-as.factor(gender)
```

```{r}
y<-c(9,3,4)
z<-c(2,6,3)
yz<-c(y,z)
yz
```

```{r}
log(10,base=10)
```

```{r}
example(log)
```

```{r}
library(mirt)
library(help=mirt)
```

```{r}
ls("package:mirt")
```

```{r}
data(package="mirt")
```

```{r}
library(hemp)
```

```{r}
?fixef
```

```{r}
library(hemp)
data("interest")
```

```{r}
data("HSQ")
```

```{r}
ls()
```

```{r}
head(rse,3)
```

```{r}
tail(rse)
```

```{r}
names(rse)
```

```{r}
rse$country
```

```{r}
str(rse)
```
```{r}
str(rse$country)
class(rse$country)
rse$country<-as.character(rse$country)
str(rse$country)
class(rse$country)
```
Skimmed through the rest in the textbook and only decided to try out a couple of things I don't remember/was curious about.

```{r}
mod1<-lm(Q1~Q2+Q3,data=rse)
names(mod1)
mod1
```
```{r}
summary(mod1)
```
```{r}
pred_values<-predict(mod1)
pred_values
```
```{r}
resid_values<-resid(mod1)
head(resid_values)
```

```{r}
par(mfrow=c(2,2),mar=c(2,4.1,2,2))
plot(mod1)
```

```{r}
plot(vocab~mathmtcs,data=interest)
```

```{r}
plot(vocab~mathmtcs,data=interest,col=gender)
```

```{r}
plot(vocab~mathmtcs,data=interest,col=gender)
lines(lowess(interest$mathmtcs,interest$vocab))
```

```{r}
verbal<-subset(interest,select=c(vocab,reading,sentcomp))
pairs(verbal)
```

```{r}
hist(interest$vocab)
```

```{r}
boxplot(interest$vocab)
```

```{r}
boxplot(interest$vocab~interest$gender)
```

```{r}
stem(interest$vocab)
```

```{r}
xyplot(vocab~reading,data=interest)
```

```{r}
xyplot(vocab~reading|gender,data=interest)
```

```{r}
install.packages("boot")
install.packages("difR")
install.packages("equate")
install.packages("faoutlier")
install.packages("GPArotation")
install.packages("lattice")
install.packages("lavaan")
install.packages("lme4")
install.packages("mirt")
install.packages("psych")
install.packages("semPlot")
install.packages("shiny")
install.packages("devtools")
devtools::install_github("cddesja/hemp")
```

```{r}
citation()
```

```{r}
citation("mirt")
```

```{r}
toBibtex(citation("mirt"))
```

