---
title: "Chapter 10 - Equating"
format: html
editor: visual
---

```{r}
library(equate)
library(hemp)
```

```{r}
vignette("equate-jss")
```

```{r}
hcre_data<-as.data.frame(table(hcre$score,hcre$form))
names(hcre_data)<-c("total","form","count")
```

```{r}
hcre_x<-as.freqtab(hcre_data[hcre_data$form=="x",c("total","count")],scales = 20:50)
hcre_y<-as.freqtab(hcre_data[hcre_data$form=="y",c("total","count")],scales = 20:50)
```

```{r}
rbind(form_x=summary(hcre_x),form_y=summary(hcre_y))
```

```{r}
plot(hcre_x)
plot(hcre_y)
```

```{r}
mean_yx<-equate(hcre_x,hcre_y,type="mean")
mean_yx
```

```{r}
mean_yx$concordance
```

```{r}
form_yx<-mean_yx$concordance
colnames(form_yx)[1]<-"total"
form_yx
```

```{r}
hcre_yx<-merge(hcre_x,form_yx)
hcre_yx
```

```{r}
linear_yx<-equate(hcre_x,hcre_y,type="linear")
linear_yx
```

```{r}
equi_yx<-equate(hcre_x,hcre_y,type="equipercentile")
equi_yx
```

```{r}
plot(equi_yx$concordance$yx~equi_yx$concordance$scale,type="p",xlab="Form X Scores",
     ylab="Adjusted X Scores on Form Y",
     ylim=c(20,55))
points(linear_yx$concordance$yx~linear_yx$concordance$scale,pch=4)
```

```{r}
negd
```

```{r}
negd$total<-rowSums(negd[,1:25])
negd$anchor<-rowSums(negd[,26:35])
negd
```

```{r}
negd_x<-freqtab(negd[1:1000,c("total","anchor")],scales=list(0:25,0:10))
negd_y<-freqtab(negd[1001:2000,c("total","anchor")],scales=list(0:25,0:10))

negd_x
negd_y
```

```{r}
plot(negd_x,xlab="Total Scores Form X",
     ylab="Common Anchor Scores Form X")
```

```{r}
smooth_x<-presmoothing(negd_x,smoothmethod = "loglinear")
smooth_y<-presmoothing(negd_y,smoothmethod = "loglinear")
smooth_x
```

```{r}
plot(smooth_x,xlab="Total Scors Form X",ylab="Common Anchor Scores Form X")
```
```{r}
negd_tucker<-equate(negd_x,negd_y,type="linear",method="tucker")
negd_tucker
```

```{r}
negd_tucker$concordance
```

