---
title: "Chapter 2 - Classical Test Theory"
format: html
editor: visual
---

```{r}
library(hemp)
```

```{r}
gender_nominal<-ifelse(interest$gender==1,"female","male")
```

```{r}
age_nominal<-cut(interest$age,breaks = seq(10,70,by=10))
```

```{r}
age_ordinal<-ordered(age_nominal)
```

```{r}
table(gender_nominal)
```

```{r}
table(age_ordinal)
```

```{r}
ftable(age_ordinal,gender_nominal)
```

```{r}
age_table<-table(age_ordinal)
```

```{r}
prop.table(age_table)
```

```{r}
prop.table(table(age_ordinal,gender_nominal))
```
```{r}
library(lattice)
barchart(age_ordinal)
```

```{r}
dotplot(age_table)
```

```{r}
age_gender_table<-table(gender_nominal,age_ordinal)
age_gender_df<-data.frame(age_gender_table)
```

```{r}
dotplot(age_ordinal~Freq|gender_nominal,age_gender_df,xlab="Frequency",ylab="age")
```

```{r}
summary(interest$vocab)
```

```{r}
qqnorm(interest$vocab,ylab = "vocab")
qqline(interest$vocab)
```

```{r}
num_miss(SAPA)
```

```{r}
split_half(SAPA,type="alternate")
```

```{r}
set.seed(1)
split_half(SAPA,type="random")
```

```{r}
split_half(SAPA,type="alternate",sb=TRUE)
```

```{r}
test_length(SAPA,r=.95,r_type = "split")
```

```{r}
test_length(SAPA,r=.95,r_type=.862)
```

```{r}
coef_alpha(SAPA)
```

```{r}
library(boot)
```

```{r}
alpha_fun<-function(data,row){
  coef_alpha(data[row,])
}
```

```{r}
alpha_boot<-boot(SAPA,alpha_fun,R=1e4)
alpha_boot
```

```{r}
plot(alpha_boot)
```

```{r}
boot.ci(alpha_boot,type=c("norm","basic","perc","bca"))
```

```{r}
cvr(N=20,n_e=17)
```

```{r}
cor(interest[,c("vocab","reading","sentcomp")])
```

```{r}
mod_old<-lm(teacher~socdom,interest)
mod_new<-lm(teacher~socdom+reading,interest)
```

```{r}
summary(mod_new)$r.squared-summary(mod_old)$r.squared
```

```{r}
anova(mod_old,mod_new)
```
```{r}
item_diff<-colMeans(SAPA,na.rm = TRUE)
round(item_diff,3)
```

